#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements
sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=0H2-TGUTwu4; 
        }
}" | sudo tee /etc/nginx/sites-enabled/default
sudo service nginx restart
