#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
sudo apt update
sudo apt -y install nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html
echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        add_header X-Served-By $HOSTNAME;
 
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
 
        error_page 404 /error404.html;
        location = /error404.html {
                root /var/www/html;
                internal;
        }
 
        location /redirect_me {
return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
  }
 
}" | sudo tee /etc/nginx/sites-enabled/default
sudo service nginx restart
