#!/usr/bin/env bash
# Installs and configures HAproxy on webserver 3, distributes requests
# using a roundrobin algorithm 

sudo apt-get update

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6

sudo apt-get install haproxy=2.6.\*

algorithm="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
        balance roundrobin
        server 57435-web-01 100.26.254.133:80 check
        server 57435-web-02 34.239.250.137:80 check
"
echo "$algorithm" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
