#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and displays "bad luck" for 4th loop "good luck" for 8th loop and "Best school" for others

	p=0
while [ $p -lt 10 ]
do
	if [ $p -eq 3 ]
	then
		echo "bad luck"
	elif [ $p -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( p++ ))
done
