#!/usr/bin/env bash
# script that configures the container

sudo service nginx stop
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
